---
- name: pull grafana image
  docker_image:
    name: grafana/grafana

- name: create grafana data volume
  docker_volume:
    state: present
    name: grafana_data

- name: create grafana network
  docker_network:
    state: present
    name: grafana_network

- name: start grafana container
  docker_container:
    name: grafana
    state: started
    image: grafana/grafana
    restart_policy: unless-stopped
    volumes:
      - grafana_data:/var/lib/grafana
    env:
      GF_SECURITY_ADMIN_PASSWORD: "{{ grafana_admin_password }}"
      GF_INSTALL_PLUGINS: "gnocchixyz-gnocchi-datasource"
    published_ports:
      - "3000:3000"
    networks:
      - name: grafana_network
    purge_networks: true
