#!/usr/bin/ansible-playbook
---
- hosts: localhost
  vars:
    docker_packages:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - python-docker-py
    docker_config:
      log-driver: journald
      storage-driver: overlay2

  tasks:
    - name: create persistent journal
      file:
        path: /var/log/journal
        state: directory
        owner: root
        group: systemd-journal
        mode: "2755"
      register: journal

    - name: ensure tmpfiles exist
      command: >-
        systemd-tmpfiles --create --prefix /var/log/journal
      changed_when: false
      when: journal is changed

    - name: reload journald
      command: >-
        systemctl restart systemd-journald
      when: journal is changed

    - name: install docker repository
      get_url:
        url: https://download.docker.com/linux/centos/docker-ce.repo
        dest: /etc/yum.repos.d/docker-ce.repo
        force: true

    - name: install docker
      package:
        name: "{{ docker_packages }}"
        state: installed

    - name: ensure docker config directory exists
      file:
        path: /etc/docker
        state: directory
        owner: root
        group: root
        mode: "0700"

    - name: write docker config
      copy:
        content: "{{ docker_config|to_nice_json }}"
        dest: /etc/docker/daemon.json

    - name: check if docker volume has been formatted
      command: >-
        blkid -s TYPE -o value /dev/vdb
      register: docker_vol
      failed_when: false
      changed_when: docker_vol.stdout != "xfs"

    - name: format docker volume
      command: >-
        mkfs -t xfs -n ftype=1 /dev/vdb
      when: docker_vol is changed

    - name: ensure docker filesystem is mounted
      mount:
        path: /var/lib/docker
        src: /dev/vdb
        fstype: xfs
        state: mounted

    - name: activate docker
      service:
        name: docker
        state: started
        enabled: true

    - name: pull grafana image
      docker_image:
        name: grafana/grafana
